# Generated by Django 2.1.1 on 2018-10-13 06:22

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_code',
            field=models.UUIDField(default=main_app.models.Family.get_family_code, editable=False),
        ),
    ]
