# Generated by Django 2.1.1 on 2018-10-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181013_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
