# Generated by Django 2.1.2 on 2018-10-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
